<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OptiCopy.Imaging</AssemblyName>
    <RootNamespace>OptiCopy.Imaging</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OptiCopy.Core\OptiCopy.Core.csproj" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>
</Project>
